import './globals.css'
import { Providers } from './provider'
import { Inter, Dela_Gothic_One } from 'next/font/google'
import { ChakraProviders } from './chakraprovider'

const inter = Inter({ subsets: ['latin'] })
const delaGothic= Dela_Gothic_One({weight:["400"],subsets:['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ChakraProviders>
              {children}
            </ChakraProviders>
        </Providers>
      </body>
    </html>
  )
}
